language_detection:
  user_prompt_template: |
    Detect the language of the following text. Respond with a short language code (e.g., en, es, fr).
    TEXT:
    ---
    {{ text }}

translation:
  user_prompt_template: |
    Translate the following text into English, preserving named entities and numbers.
    TEXT:
    ---
    {{ text }}

summarization:
  user_prompt_template: |
    Summarize the following text in 1-3 sentences:
    ---
    {{ text }}

classification_reasoning:
  user_prompt_template: |
    Explain why the content was classified as {{ docTypeCode }}: {{ docTypeDescription }}.
    Provide matching keywords and a short sentence.

risk_detection:
  user_prompt_template: |
    List potential regulatory/risk flags present in the text, if any, as a JSON array.

metadata_extraction:
  user_prompt_template: |
    Extract metadata (customer ID, dates in YYYY-MM-DD, amounts with currency) as JSON.
